package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type matrixRow struct {
	RequirementID string
	CoverageType  string
	TestRefs      string
	Status        string
	Notes         string
}

var (
	requirementIDPattern      = regexp.MustCompile("`([A-Z][A-Z0-9-]*-\\d{3})`")
	matrixManagedNotice       = "> Generated by `go run ./cmd/sync_test_matrix -apply`. DO NOT EDIT MANUALLY."
)

func main() {
	apply := flag.Bool("apply", false, "write updates to docs/TEST_MATRIX.md")
	flag.Parse()

	root, err := os.Getwd()
	if err != nil {
		exitf("getwd: %v", err)
	}

	matrixPath := filepath.Join(root, "docs", "TEST_MATRIX.md")
	requirementFiles, err := filepath.Glob(filepath.Join(root, "docs", "requirements", "*.md"))
	if err != nil {
		exitf("glob requirements: %v", err)
	}
	sort.Strings(requirementFiles)

	ids, err := collectRequirementIDs(requirementFiles)
	if err != nil {
		exitf("collect requirement ids: %v", err)
	}

	refs, err := collectTaggedTestRefs(root)
	if err != nil {
		exitf("collect tagged test refs: %v", err)
	}

	updated, changed, err := updateMatrix(matrixPath, ids, refs)
	if err != nil {
		exitf("update matrix: %v", err)
	}

	if !*apply {
		if changed {
			fmt.Println("docs/TEST_MATRIX.md needs updates. Run: go run ./cmd/sync_test_matrix -apply")
			os.Exit(1)
		}
		fmt.Println("docs/TEST_MATRIX.md is up to date")
		return
	}

	if !changed {
		fmt.Println("docs/TEST_MATRIX.md is already up to date")
		return
	}

	if err := os.WriteFile(matrixPath, []byte(updated), 0o644); err != nil {
		exitf("write matrix: %v", err)
	}

	fmt.Println("updated docs/TEST_MATRIX.md")
}

func collectRequirementIDs(files []string) ([]string, error) {
	seen := map[string]struct{}{}
	ids := make([]string, 0)

	for _, path := range files {
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		matches := requirementIDPattern.FindAllStringSubmatch(string(content), -1)
		for _, m := range matches {
			id := m[1]
			if _, exists := seen[id]; exists {
				continue
			}
			seen[id] = struct{}{}
			ids = append(ids, id)
		}
	}

	if len(ids) == 0 {
		return nil, errors.New("no requirement IDs found")
	}

	return ids, nil
}

func collectTaggedTestRefs(root string) (map[string][]string, error) {
	refs := map[string][]string{}

	files, err := collectSupportedTestFiles(root)
	if err != nil {
		return nil, err
	}

	swiftFiles := make([]string, 0)
	for _, path := range files {
		if strings.HasSuffix(path, ".swift") {
			swiftFiles = append(swiftFiles, path)
		}
	}

	swiftTestsByFile, err := parseSwiftTestsWithSwiftSyntax(root, swiftFiles)
	if err != nil {
		return nil, err
	}

	for _, path := range files {
		if strings.HasSuffix(path, "_test.go") {
			if err := collectFromGoFile(root, path, refs); err != nil {
				return nil, err
			}
			continue
		}

		if strings.HasSuffix(path, ".swift") {
			if err := collectFromSwiftFile(root, path, swiftTestsByFile[path], refs); err != nil {
				return nil, err
			}
		}
	}

	for id := range refs {
		sort.Strings(refs[id])
	}

	return refs, nil
}

func collectSupportedTestFiles(root string) ([]string, error) {
	files := make([]string, 0)
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".derived" || name == "bin" {
				return filepath.SkipDir
			}
			return nil
		}

		if !isSupportedTestFile(path) {
			return nil
		}

		files = append(files, path)
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Strings(files)
	return files, nil
}

func isSupportedTestFile(path string) bool {
	base := filepath.Base(path)
	if strings.HasSuffix(base, "_test.go") {
		return true
	}
	if strings.HasSuffix(base, ".swift") && strings.Contains(base, "Tests") {
		return true
	}
	return false
}

func collectFromGoFile(root, path string, refs map[string][]string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, path, content, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse go test file %s: %w", path, err)
	}

	rel, err := filepath.Rel(root, path)
	if err != nil {
		return fmt.Errorf("rel path %s: %w", path, err)
	}
	rel = filepath.ToSlash(rel)

	lines := splitLines(string(content))
	for _, decl := range parsed.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !isGoTestFunction(fn) {
			continue
		}

		pos := fset.Position(fn.Pos())
		if pos.Line <= 0 {
			continue
		}
		testLineIndex := pos.Line - 1

		for _, id := range collectAdjacentTagIDs(lines, testLineIndex) {
			addRequirementRef(refs, id, rel, fn.Name.Name)
		}
	}

	return nil
}

func collectFromSwiftFile(root, path string, tests []swiftTestInfo, refs map[string][]string) error {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return fmt.Errorf("rel path %s: %w", path, err)
	}
	rel = filepath.ToSlash(rel)

	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	lines := splitLines(string(content))

	for _, test := range tests {
		lineIndex := test.Line - 1
		if lineIndex < 0 || lineIndex >= len(lines) {
			continue
		}
		for _, id := range collectAdjacentTagIDs(lines, lineIndex) {
			addRequirementRef(refs, id, rel, test.Name)
		}
	}

	return nil
}

type swiftTestInfo struct {
	Name string `json:"name"`
	Line int    `json:"line"`
}

func parseSwiftTestsWithSwiftSyntax(root string, swiftFiles []string) (map[string][]swiftTestInfo, error) {
	if len(swiftFiles) == 0 {
		return map[string][]swiftTestInfo{}, nil
	}

	args := []string{
		"run",
		"--package-path",
		filepath.Join(root, "cmd", "sync_test_matrix", "swift_parser"),
		"sync-test-matrix-swift-parser",
	}
	args = append(args, swiftFiles...)

	cmd := exec.Command("swift", args...)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("swift syntax parser failed: %s", strings.TrimSpace(string(ee.Stderr)))
		}
		return nil, fmt.Errorf("run swift syntax parser: %w", err)
	}

	testsByFile := map[string][]swiftTestInfo{}
	if err := json.Unmarshal(out, &testsByFile); err != nil {
		return nil, fmt.Errorf("decode swift syntax parser output: %w", err)
	}

	return testsByFile, nil
}

func isGoTestFunction(fn *ast.FuncDecl) bool {
	if fn == nil || fn.Recv != nil || fn.Name == nil {
		return false
	}
	return strings.HasPrefix(fn.Name.Name, "Test")
}

func addRequirementRef(refs map[string][]string, requirementID, relPath, testName string) {
	if requirementID == "" || relPath == "" || testName == "" {
		return
	}
	ref := fmt.Sprintf("`%s` (`%s`)", relPath, testName)
	if !contains(refs[requirementID], ref) {
		refs[requirementID] = append(refs[requirementID], ref)
	}
}

func splitLines(content string) []string {
	trimmed := strings.TrimRight(content, "\n")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "\n")
}

func collectAdjacentTagIDs(lines []string, testLine int) []string {
	ids := make([]string, 0)

	for i := testLine - 1; i >= 0; i-- {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" {
			continue
		}
		if !isLineComment(trimmed) {
			break
		}
		ids = append(ids, extractTagIDsFromCommentLine(trimmed)...)
	}

	for i := testLine + 1; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" {
			continue
		}
		if !isLineComment(trimmed) {
			break
		}
		ids = append(ids, extractTagIDsFromCommentLine(trimmed)...)
	}

	return uniqueStrings(ids)
}

func isLineComment(trimmed string) bool {
	return strings.HasPrefix(trimmed, "//")
}

func extractTagIDsFromCommentLine(trimmed string) []string {
	line := strings.TrimSpace(trimmed)
	if !strings.HasPrefix(line, "//") {
		return nil
	}
	body := strings.TrimSpace(strings.TrimPrefix(line, "//"))
	if len(body) < 4 || strings.ToLower(body[:4]) != "@req" {
		return nil
	}
	payload := strings.TrimSpace(body[4:])
	if payload == "" {
		return nil
	}

	ids := make([]string, 0)
	for _, part := range strings.Split(payload, ",") {
		candidate := strings.TrimSpace(part)
		if isRequirementID(candidate) {
			ids = append(ids, candidate)
		}
	}
	return uniqueStrings(ids)
}

func isRequirementID(value string) bool {
	if value == "" {
		return false
	}
	parts := strings.Split(value, "-")
	if len(parts) < 2 {
		return false
	}
	suffix := parts[len(parts)-1]
	if len(suffix) != 3 {
		return false
	}
	for _, r := range suffix {
		if r < '0' || r > '9' {
			return false
		}
	}

	prefix := strings.Join(parts[:len(parts)-1], "-")
	if prefix == "" {
		return false
	}
	for i, r := range prefix {
		if i == 0 {
			if r < 'A' || r > 'Z' {
				return false
			}
			continue
		}
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' {
			continue
		}
		return false
	}

	return true
}

func uniqueStrings(items []string) []string {
	seen := make(map[string]struct{}, len(items))
	result := make([]string, 0, len(items))
	for _, item := range items {
		if item == "" {
			continue
		}
		if _, exists := seen[item]; exists {
			continue
		}
		seen[item] = struct{}{}
		result = append(result, item)
	}
	return result
}

func updateMatrix(matrixPath string, requirementIDs []string, refs map[string][]string) (string, bool, error) {
	content, err := os.ReadFile(matrixPath)
	if err != nil {
		return "", false, fmt.Errorf("read %s: %w", matrixPath, err)
	}

	lines := strings.Split(string(content), "\n")
	lines = ensureManagedNotice(lines)
	headIdx := -1
	sepIdx := -1
	for i, line := range lines {
		if strings.HasPrefix(line, "| Requirement ID |") {
			headIdx = i
			if i+1 < len(lines) && strings.HasPrefix(lines[i+1], "| ---") {
				sepIdx = i + 1
			}
			break
		}
	}
	if headIdx == -1 || sepIdx == -1 {
		return "", false, errors.New("coverage table header not found")
	}

	endIdx := sepIdx + 1
	for endIdx < len(lines) {
		if !strings.HasPrefix(strings.TrimSpace(lines[endIdx]), "|") {
			break
		}
		endIdx++
	}

	currentRows := parseRows(lines[sepIdx+1 : endIdx])
	rowByID := map[string]matrixRow{}
	for _, row := range currentRows {
		rowByID[row.RequirementID] = row
	}

	newRows := make([]string, 0, len(requirementIDs))
	for _, id := range requirementIDs {
		existing := rowByID[id]
		coverageType := fallback(existing.CoverageType, "Automated")
		notes := fallback(existing.Notes, "-")

		testRefs := existing.TestRefs
		status := existing.Status
		if tagged := refs[id]; len(tagged) > 0 {
			testRefs = strings.Join(tagged, ", ")
			if status == "" || status == "Gap" {
				status = "Covered"
			}
		} else {
			testRefs = fallback(testRefs, "-")
			if status == "" {
				status = "Gap"
			}
		}

		newRows = append(newRows, fmt.Sprintf("| `%s` | %s | %s | %s | %s |", id, coverageType, testRefs, status, notes))
	}

	newLines := make([]string, 0, len(lines)-len(currentRows)+len(newRows))
	newLines = append(newLines, lines[:sepIdx+1]...)
	newLines = append(newLines, newRows...)
	newLines = append(newLines, lines[endIdx:]...)

	updated := strings.Join(newLines, "\n")
	return updated, updated != string(content), nil
}

func ensureManagedNotice(lines []string) []string {
	for _, line := range lines {
		if strings.TrimSpace(line) == matrixManagedNotice {
			return lines
		}
	}

	insertAt := 0
	if len(lines) > 0 {
		insertAt = 1
		if len(lines) > 1 && strings.TrimSpace(lines[1]) == "" {
			insertAt = 2
		}
	}

	updated := make([]string, 0, len(lines)+2)
	updated = append(updated, lines[:insertAt]...)
	updated = append(updated, matrixManagedNotice, "")
	updated = append(updated, lines[insertAt:]...)
	return updated
}

func parseRows(lines []string) []matrixRow {
	rows := make([]matrixRow, 0, len(lines))
	for _, line := range lines {
		parts := splitMarkdownRow(line)
		if len(parts) != 5 {
			continue
		}
		id := strings.Trim(parts[0], "`")
		if id == "" {
			continue
		}
		rows = append(rows, matrixRow{
			RequirementID: id,
			CoverageType:  strings.TrimSpace(parts[1]),
			TestRefs:      strings.TrimSpace(parts[2]),
			Status:        strings.TrimSpace(parts[3]),
			Notes:         strings.TrimSpace(parts[4]),
		})
	}
	return rows
}

func splitMarkdownRow(line string) []string {
	trimmed := strings.TrimSpace(line)
	if !strings.HasPrefix(trimmed, "|") || !strings.HasSuffix(trimmed, "|") {
		return nil
	}
	inner := strings.TrimSuffix(strings.TrimPrefix(trimmed, "|"), "|")
	raw := strings.Split(inner, "|")
	out := make([]string, 0, len(raw))
	for _, p := range raw {
		out = append(out, strings.TrimSpace(p))
	}
	return out
}

func contains(items []string, target string) bool {
	for _, item := range items {
		if item == target {
			return true
		}
	}
	return false
}

func fallback(value, defaultValue string) string {
	if strings.TrimSpace(value) == "" {
		return defaultValue
	}
	return value
}

func exitf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
